### ISSUE TITLE
Mod 0 Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [chakeresa/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] Directories are named correctly. 
- [x] Files are named correctly.
- [x] Files and directories are structured correctly. 
- [x] Initial commit was made.
- [x] Initial commit was pushed to GitHub.

#### Part II: Top Down Design

- [x] Larger processes were broken into smaller layers.
- [x] Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
- [x] Changes were pushed to Github. 

#### Part III: Classes in a System

- [x] Directories and files were named and structured correctly.
- [x] The attributes chosen for **Class #1** represent states or characteristics.
> Since `average_rating` is a calculation, consider moving that to the methods and including a `ratings` array as an attribute that you could use when you perform the average rating calculation.
- [x] The attributes chosen for **Class #2** represent states or characteristics.
> (same comment for the above class)
- [x] The attributes chosen for **Class #3** represent states or characteristics.
- [x] The methods chosen for **Class #1** represent behaviors or actions.
- [x] The methods chosen for **Class #2** represent behaviors or actions.
- [x] The methods chosen for **Class #3** represent behaviors or actions.
- [x] Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
- [ ] Individual changes were added and committed separately with a properly formatted commit message. 
> Your commit message looks great. In the rubric, it refers to `...committed each set of changes separately...`. It looks like there was one commit made for all three files. 
- [x] Changes were pushed to Github. 

**Mod 0 Technical Assessment Results**

* [x]  Technical Ready
* [ ]  Conditional Ready
* [ ]  Not ready
